### ISSUE TITLE
option to copy username/password to clipboard.

### ISSUE THREAD

**Issue by james-lawrence** [dannyvankooten/browserpass#105]
for pages that fail to autofill a nice feature would be to allow copying fields to the clipboard.

**Comment by bddenhartog** [comment]
Personally, I'd like to see this implemented either with an icon/button to click (maybe the favicon? it could be replaced with a copy icon on row hover), or simply via right-clicking the row. Anything else, IMHO, would complicate the workflow of getting the password beyond alt+tabbing to a terminal and typing out the `pass` command.

**Comment by maximbaz** [comment]
Right-clicking on a row is not intuitive, I'm afraid nobody will guess that such functionality exists 🙂

My suggestions:
- Have two buttons on the right side of every entry, one to copy username, another to copy password.
- Handle <kbd>Ctrl+C</kbd> (is it <kbd>Cmd+C</kbd> on Mac?) and copy the password of the currently focused entry (this item is for keyboard users).

**Comment by bddenhartog** [comment]
> Right-clicking on a row is not intuitive

That's most certainly a subjective statement. Right-clicking was the first thing I did when imagining how a "copy" function would work - users are already used to interacting with the plugin with their mouse, wouldn't a keyboard shortcut detract from the experience they're used to?

**Comment by maximbaz** [comment]
We have a very powerful support for keyboard users, definitely not everyone is interacting with the plugin with the mouse 🙂

That's why I want to see this feature implemented in two ways, for mouse users and for keyboard users. We can discuss how to best implement it for mouse users, we can discuss how to best implement it for keyboard users, but whatever we choose for "mouse approach" will not substitute the "keyboard approach". 

Now, for those who use mouse, we have two ideas now - right click on an entry, or left-clicking on one of two new buttons. I vote for the buttons because it is more intuitive, a random user who sees such buttons can immediately understand what they do. This is very approximate on how I imagine it:

![browserpass_icons](https://user-images.githubusercontent.com/1177900/31216018-4203976a-a9b2-11e7-81d8-0601daa42009.png)

For those who use keyboard, <kbd>Ctrl+C</kbd> (<kbd>Cmd+C</kbd> on Mac?) is the only idea that we have so far, and seems quite intuitive to me 🙂

**Comment by Weker01** [comment]
Is someone working on this?

**Comment by maximbaz** [comment]
Don't think so, wanna give it a try? 😉

**Comment by Weker01** [comment]
Time to dive into a Codebase I know nothing about. I will try implementing something on the chrome side first.

**Comment by maximbaz** [comment]
Awesome! Feel free to create an early PR and ask any questions, I got acquainted with the codebase recently and can give you some hints.

Good news, the code is shared across browsers, so you only need to touch the files in `chrome` folder 🙂 

[CONTRIBUTING.md](https://github.com/dannyvankooten/browserpass/blob/master/CONTRIBUTING.md) should be of some help post-processing the javascript code.

**Comment by maximbaz** [comment]
Thanks to @Weker01 this has been implemented 🎉 We have now buttons to copy username and password to clipboard. The keyboard shortcuts are also available, <kbd>Ctrl+C</kbd> copies password and <kbd>Shift+C</kbd> copies username.

The new release will be made later today that includes this feature 😉 

![image](https://user-images.githubusercontent.com/1177900/32672317-df64694e-c64a-11e7-9e04-230357b4be30.png)
