### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by emersion** [dannyvankooten/browserpass#116]
Addon is unreadable when enabling dark theme.

How to reproduce : choose Customize > Themes > Compact dark

This is also the default Firefox Dev Edition theme.

![screenshot from 2017-08-09 15-40-29](https://user-images.githubusercontent.com/506932/29124447-39ec422c-7d19-11e7-8ea3-0d19627fc3fd.png)

**Comment by 00dani** [comment]
This issue isn't as bad under MacOS, which uses readable colours:

![screen shot 2017-09-21 at 08 48 36](https://user-images.githubusercontent.com/610876/30671324-aed34174-9ea9-11e7-818a-8c99ad9e7a92.png)

A dark theme would still be nice to have nonetheless though, since everything around it is dark. 😉

**Comment by maximbaz** [comment]
Thanks to @aeris and #166 the colors are finally fixed when using dark theme. 

Implementing a dark theme for the extension is a different topic though, definitely out of scope of this ticket. 

I couldn't find anything that would allow detecting what color scheme the browser is using (does anyone know any other extension, that adapts its own colors based on the currently used browser theme?). 

Perhaps the only way is to add a theme selector to our own options page, and implement a second stylesheet for dark theme, and somehow dynamically inject in the popup one or another stylesheet based on the user preference.

If someone wants to continue discussion on this, please create a separate ticket (or better yet, a PR 😛).
