### ISSUE TITLE
Browserpass tries to install older version of Go when installing from AUR

### ISSUE THREAD

**Issue by simplycycling** [dannyvankooten/browserpass#124]
I tried installing Browserpass via the Arch Linux AUR, and it wanted to install Go 1.8.3. I already have Go 1.9 installed, and assuming you even can have two versions of Go installed on a system (I'm not sure that you can), I don't want to have to worry about two versions.

Action - I tried installing Browserpass with the following command:

pacaur -S browserpass

Result - I aborted after getting the following output:

:: Package browserpass not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (1) browserpass-1.0.6-2  
Repo Packages (1) go-2:1.8.3-1  

Repo Download Size:    41.36 MiB
Repo Installed Size:  205.46 MiB

:: Proceed with installation? [Y/n] n

Desired result - it would be great if it didn't try to install Go, when Go is already installed.

**Comment by maximbaz** [comment]
[AUR package](https://aur.archlinux.org/packages/browserpass/) is handled by someone else, not by this repo, so you better leave a comment over there. 

But since I also use ArchLinux, I can tell you that referencing other ArchLinux packages is the standard way that pacaur or pacman would use to deal with dependencies. 

You should probably remove your custom installation of `go` and use one of the available packages, either use the `extra/go` which is already updated to `1.9`, or use `aur/go-git` to be on the latest and greatest version.
