### ISSUE TITLE
Wrong endianness on native messaging response?

### ISSUE THREAD

**Issue by chrboe** [dannyvankooten/browserpass#150]
### General information

* Operating system + version: `n/a`
* Browser + version: `n/a`
* If installed an official release, put a release version: `n/a`
* If built from sources, put a commit id (`$ git describe --always`): b9b9173
* Browserpass extension version as reported by your browser: `n/a`

---

I played around with the native messaging protocol for a little bit and noticed something rather odd about the way browserpass sends its responses back to the browser.

Normally, the first 4 bytes of the message are supposed to be the length of the message, represented in Little Endian. That means a message could look like this:
```
$ xxd -g 1 request.hex
00000000: 00 00 00 2d 7b 22 61 63 74 69 6f 6e 22 3a 20 22  ...-{"action": "
00000010: 73 65 61 72 63 68 22 2c 22 64 6f 6d 61 69 6e 22  search","domain"
00000020: 3a 22 77 77 77 2e 67 69 74 68 75 62 2e 63 6f 6d  :"www.github.com
00000030: 22 7d                                            "}
```

Notice the first four bytes, `00 00 00 2d`. Since the length of this message payload is 45 (=`0x2D`) bytes, we put the length in the first 4 bytes of the request.

Now look at the response from browserpass:

```
$ ./browserpass < request.hex > response.hex
$ xxd -g 1 response.hex
00000000: 17 00 00 00 5b 22 67 69 74 68 75 62 2e 63 6f 6d  ....["github.com
00000010: 5c 5c 63 68 72 62 6f 65 22 5d 0a                 \\chrboe"].
```

The first bytes are `17 00 00 00`. Isn't that the wrong way around? I'm pretty sure it should be `00 00 00 17`. Chrome doesn't complain about it in any way, so it can't be **that** wrong I guess. Is this a bug that Chrome just doesn't care about or am I missing something else here?

**Comment by maximbaz** [comment]
Isn't `00 00 00 2d` actually Big Endian? I belive `2d 00 00 00` is Little Endian representation of `45` 🙂

So I'd rather ask, why `browserpass` accepts Big Endian and responds with Little Endian? :thinking: 

[...is preceded with 32-bit message length in **native byte order**](https://developer.chrome.com/apps/nativeMessaging#native-messaging-host-protocol) - on Intel CPU the native order is Little Endian, so.. the response is correct, but the input seems wrong. How come it even works? :smile:

**Comment by maximbaz** [comment]
Put `fmt.Println(n)` in `browserpass.go:49` to print the parsed number, and you will see that when you pass `00 00 00 2d`, the parsed value is `754974720` - because the parser expects Little Endian, and `00 00 00 2d` is Big Endian format. The `n` of `754974720` is big and covers your JSON entirely, that's why it is accepted by browserpass.

However, in order to correctly compose a message for `browserpass`, you need to make two adjustments.

1. Use Little Endian format, i.e. `2d 00 00 00`.
2. Add `\n` (`0a`) to the end of the message, which also increases the size from `2d` to `2e` (try without this step, see what happens)

In other words, this is the correct message:

```
❯  xxd -g 1 request.hex.bin
00000000: 2e 00 00 00 7b 22 61 63 74 69 6f 6e 22 3a 22 73  ....{"action":"s
00000010: 65 61 72 63 68 22 2c 22 64 6f 6d 61 69 6e 22 3a  earch","domain":
00000020: 22 77 77 77 2e 67 69 74 68 75 62 2e 63 6f 6d 22  "www.github.com"
00000030: 7d 0a                                            }.
```

```
❯  ./browserpass < request.hex.bin
46
j["personal/github.com/maximbaz"]
```

`46` is a proof that `2e 00 00 00` was correctly parsed, and you see the correct output.

Does that answer the question @chrboe? 🙂

Thanks for the question, it was interesting to investigate 🙂

**Comment by chrboe** [comment]
>Isn't 00 00 00 2d actually Big Endian? 

Right, I got that mixed up :) The question still remains the same though.

> The n of 754974720 is large and covers your JSON entirely, that's why it is accepted by browserpass.

Well it all seems logical now :D Thanks for investigating/explaining.

**Comment by maximbaz** [comment]
Just wanted to say, [chrboe/native.pl](https://github.com/chrboe/native.pl) is an awesome tool, helps a lot at debugging the host application 🙂
