### ISSUE TITLE
Homebrew formula for native binary

### ISSUE THREAD

**Issue by zsau** [dannyvankooten/browserpass#173]
It would be nice to be able to install the native binary via Homebrew, for easy updating.

**Comment by crapp** [comment]
Please also consider supporting macports https://www.macports.org

**Comment by maximbaz** [comment]
Would anyone want to volunteer helping with any of these suggestions? :)

I will be happy to advise on any questions, but since I don't have a Mac and since it is a community project, if any of these ideas ever get implemented, the implementation will come from the community. 

I'll keep this ticket open for a while, hoping that it will draw attention of other Mac users, but if nobody wants to help I'll have to close it.

**Comment by crapp** [comment]
I will have a look if I can write a port file for macports. I have done this in the past so that shouldn't be the problem. I am not so sure about the installation process. The binary has to be copied for every supported browser in a specific directory. I think I'd rather install the binary to the default system location (/opt/local/bin) and create symlinks. I'll give it a try next weekend...

**Comment by maximbaz** [comment]
That would be awesome! 

It isn't normally needed to copy the binary, we usually put one binary in one place (like in `/usr/bin` on linux) and let different browsers know where to find the binary. Browsers will not look in $PATH, they use what is declared in the host.json file, [right here](https://github.com/dannyvankooten/browserpass/blob/4bc4eb6118855f91fcc705e466e108525370c7a4/chrome/host.json#L4).

I recommend checking out installation instructions in [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=browserpass), the `build()` function there takes care of compiling a binary, and the `package()` function takes care of placing various files to the correct location on the system.

Another source of truth would of course be our own [install.sh](https://github.com/dannyvankooten/browserpass/blob/master/install.sh) that we ship together with the release.

**Comment by zsau** [comment]
I'm working on a brew formula, but Homebrew doesn't allow installing files outside the package sandbox. So my plan is to install both the native binary and the `install.sh` file (as `browserpass-setup` or such) and instruct the user to run the latter upon installation. The host manifest files would be initially installed to `$HOMEBREW_PREFIX/share/browserpass/`, for the setup script to copy from.

For that to work, I'll need the brew formula to do a search-and-replace on `install.sh` to tell it where to find the native binary and the host manifest files. That would be awkward as-is since the script assumes both will be found in the same place, `$DIR`. @maximbaz, would you consider changing `install.sh` to use two separate vars for the binary dir and the manifest dir, so those locations can be easily swapped out? I can make a pull request if you like, though it's a pretty trivial change.

**Comment by maximbaz** [comment]
I recommend not using install.sh for this, the script is really only for manual installations. Have a look at AUR package that I mentioned above, specifically `package` function.

**Comment by maximbaz** [comment]
Or "package sandbox" means only the folder with the binary? In which case, yeah I see what you mean... Sounds sensible, but let me also think about it and I'll get back to you. There are simply a few other requests for install.sh, I want to make sure they will not break what you are doing here in future.

**Comment by maximbaz** [comment]
@zsau I wouldn't like automated packages to depend on `install.sh`, first because it will change in the future in one or another way and I don't want to worry about potential backwards compatibility issues, but also since it's a package, it should just know how to configure browserpass as much as possible without my manual intervention.

I'm not familiar much with brew, but in [this example](https://docs.brew.sh/Formula-Cookbook.html#grab-the-url) I see some `system` calls. Can you use them to copy the json files to correct locations, or better yet, use symlinks?

I imagine the brew install the following files:

```
/usr
    /bin/browserpass
    /share/browserpass/*.json
```

and then you can do the following:

```
mkdir -p /Library/Google/Chrome/NativeMessagingHosts
ln -s /usr/share/browserpass/chrome-host.json /Library/Google/Chrome/NativeMessagingHosts/$APP_NAME.json

... (the same for other files and browsers)

```

That's essentially what aur package is doing, except that it keeps track of these files and automatically removes them upon uninstallation of browserpass. If there is a way to define commands to run on removal, you can also cleanup these files.

**Comment by zsau** [comment]
I'd prefer that too, but apparently it's not possible: https://discourse.brew.sh/t/installing-files-to-library/1284.

**Comment by maximbaz** [comment]
I'm curious how it will know what `system` call is going to do? 🙂 Could you actually try to see if what that person mentioned (about sandbox not allowing) is actually true?

If this is indeed impossible, yes please go ahead and extend the `install.sh` to how ever you need it to be. I'll keep in mind to ping you in case it will change, so that you have time to adapt the brew formula if needed.

**Comment by zsau** [comment]
Any attempt to write to paths outside the sandbox results in a permission error.

**Comment by zsau** [comment]
About install.sh, would you accept a change that makes it do something similar to the AUR package, installing the actual JSON files to someplace like `$PREFIX/share/browserpass/` and symlinking to them from the browser's `NativeMessagingHosts` dir?

**Comment by maximbaz** [comment]
I'm not sure about symlinking, because I'm not sure how people use the script, i.e. if it is possible that someone will start having broken symlinks because they delete their "installation dir" after they install the app... 

Let's keep copying the files, but do your change to separate binary dir and manifests dir.

**Comment by zsau** [comment]
The manifest already acts like a symlink, in that the JSON file references a binary at a specific path (which must exist for the plugin to work). Also I doubt many people blindly delete dirs in `$PREFIX/share` without knowing what uses them.

But it's not a big deal either way. If you still don't like the idea, I'll keep copying the JSON files and just add the binary/manifest dir distinction as discussed.

**Comment by maximbaz** [comment]
I was more thinking like people might download release archive, unarchive the files, copy the binary to /usr/bin/browserpass, run `install.sh` and then delete the downloaded release archive. I also do something like this during development, e.g. compile things to generate manifests, run `install.sh` directly in the source repo, but later clean repo from autogenerated files (which removes json files).

**Comment by zsau** [comment]
The symlinks wouldn't be affected by doing that. I'm suggesting that `install.sh` copy the JSON files to `$PREFIX/share/browserpass` and then create symlinks pointing to those files inside the `NativeMessagingHosts` dir(s). That way if the JSON files need to be updated at any point, upgrading via homebrew wouldn't require re-running the install script.

**Comment by zsau** [comment]
On second thought, I'm not sure what I was thinking since the homebrew formula would need to copy the JSON files to the shared directory, so that part can't be done by `install.sh`. I'll keep the copying approach; sorry for the noise.

**Comment by maximbaz** [comment]
How about just printing commands for user to execute after installation is done? So you install binary and all json files to somewhere, rename what is possible rename, and then print messages "now please copy-paste and run these commands".

I did something like this in [a different aur package](https://aur.archlinux.org/cgit/aur.git/tree/yubikey-touch-detector.install?h=yubikey-touch-detector), just a bunch of prints after installation.

**Comment by zsau** [comment]
I considered doing that, but the script seems a little more user-friendly and less error-prone.

The Homebrew formula's pretty much ready, as soon as #190 makes it into a release.

**Comment by maximbaz** [comment]
I was going to make a new release as soon as #188 is merged, is it okay to wait for it? 

/cc @Weker01

**Comment by zsau** [comment]
No problem!

**Comment by maximbaz** [comment]
@zsau 2.0.8 was just released, please test your formula and close this issue if everything is working fine 😉

**Comment by zsau** [comment]
https://github.com/Homebrew/homebrew-core/pull/21039

Thanks for the help!

**Comment by maximbaz** [comment]
@zsau could you ping me when you manage to get the formula merged, in one place or another? I'd like to rewrite the installation section of the README and mention all available packages as a preferred way of installation (so far I'm only aware of existing packages for ArchLinux and NixOS).

**Comment by zsau** [comment]
Looks like it's not going to be accepted by Homebrew, and frankly I have no will to mess with a cask after wasting a bunch of time on the HB formula. I also just found out that `gopass` now has native messaging support built-in (already used by the add-on `gopassbridge`), so I'm even less inclined to put in more work on this. Sorry ;(

**Comment by maximbaz** [comment]
It's a shame that homebrew aren't willing to accept this. Thanks for trying anyway :+1: 

Wow, good finding about built-in native messaging support in gopass, I'm very curious about it now 🙂
