### ISSUE TITLE
browserpass does not fill in credentials on adobe.com

### ISSUE THREAD

**Issue by gurucubano** [dannyvankooten/browserpass#177]
### General information

* Operating system + version: FreeBSD 12-CURRENT, amd64
* Browser + version: FF 52.0 (64-bit)
* If installed an official release, put a release version: 1.0.6
* If built from sources, put a commit id (`$ git describe --always`): 
* Browserpass extension version as reported by your browser: 1.0.5

---

### Exact steps to reproduce the problem
1. go to the login page via https://adobe.com/  --> login
2. click on the browserpass icon, it finds the entry in the .password-store
3. click on the entry
4. the username field of the login mask stays empty, dto. the pawword field; the cursor is moved from the username to the password field

### What should happen?
credentials should filled in

### What happened instead?
only the cursor is moved to the password field

the credentials itself are fine:

$ pass web/adobeid-na1.services.adobe.com
XXXXXXXXXXXXXXXXX
Username: XXXXXXXXXXXXXXXXX

**Comment by maximbaz** [comment]
Hey @gurucubano, thanks for reporting this. You are using very old version, please upgrade to v2 as there are so many issues fixed and improved. The issue with filling out credentials on adobe.com is also fixed, I've just double checked.

The current version is [2.0.5](https://github.com/dannyvankooten/browserpass/releases/tag/2.0.5), and the browser extension is [different](https://github.com/dannyvankooten/browserpass/issues/117#issuecomment-333234195) now.

----

I noticed however that auto-submit doesn't work on adobe.com, for that I'll keep the issue open and see if this is something I can fix as well. Right now, username and password is being filled in, but you have to additionally press <kbd>Enter</kbd> to submit the form.

**Comment by maximbaz** [comment]
Autosubmit will work since 2.0.6, no need to additionally press <kbd>Enter</kbd> anymore (unless you disabled this functionality in options) - thanks again for reporting. 

Let me know if you encounter issues with upgrading or if you discover another website where autofill or autosumit is not working on the latest version!

**Comment by gurucubano** [comment]
I was wrong with the version; I have it from git around July 3 and it says:

[guru@c720-r314251 ~/go/src/github.com/dannyvankooten/browserpass]$ git describe --always
a559fdb

which version is this?

**Comment by maximbaz** [comment]
I can tell that it's still an old one, because browser extension `browserpass` is most probably incompatible with v2, and `browserpass-ce` is incompatible with v1. Filling credentials on the websites requires a new frontend (new browser extension called `browserpass-ce`), and that in turn will force you to install v2 backend.
