### ISSUE TITLE
RFC: Better method of displaying OTP

### ISSUE THREAD

**Issue by ashkitten** [dannyvankooten/browserpass#178]
Currently, to display the OTP we just put it in an alert dialog. This is not ideal, as in most browsers it's necessary to close the alert dialog in order to interact with the page, and the text inside an alert is not generally selectable for copying. What would be a better solution for displaying the OTP?

This sort of goes along with #105, and could be implemented similarly I think. My idea of this would be that it displays an overflow menu with options of what to copy to the clipboard, and OTPs could be one of those options.

**Comment by maximbaz** [comment]
The text is selectable in my Chromium, it is a pity that it is not selectable in other browsers...

![image](https://user-images.githubusercontent.com/1177900/31554940-78904e20-b03f-11e7-981f-0759262b5358.png)

But regardless, I agree that this is not the most optimal solution 🙂 

What I'd like to point out is that we can't know beforehand if a record has OTP token or not, unless we decrypt every record just to see if there is a OTP string in it (which we will not do). And since we cannot know which records have an OTP string and which don't, we'd have to show this button "Copy OTP code" in front of every single record, even those that don't have it... This will be confusing. Especially for those people who don't store OTP codes in pass 🙂

/cc @qbit who created the initial implementation for OTP codes.

**Comment by qbit** [comment]
The other issue that the alert solves is with the otp entry being on a different page. The alert "hangs" the loading of the next page allowing for copying. I agree it isn't ideal, but I still don't know a better way to do it :D

**Comment by ashkitten** [comment]
What if we had a selectable box in the corner of the page with the OTP (which could even update after it times out) and waits until it is dismissed?

**Comment by maximbaz** [comment]
This idea I like better. 

Who wants to try making a pull request for this? 🙂 I'll be happy to help reviewing and merging the code, but you guys are only two users of browserpass that I know who use OTP, so... 😉

**Comment by ashkitten** [comment]
I can work on this later today or tomorrow if I can figure out the codebase, haven't even looked at it yet :P

A point in the right direction would be useful as well.

**Comment by qbit** [comment]
[Here](https://github.com/dannyvankooten/browserpass/blob/master/chrome/inject.browserify.js#L206) is where it currently alerts from. I haven't looked into it too much, but I am guessing you will have to not use the inject portion of the code.. maybe put it in [this](https://github.com/dannyvankooten/browserpass/blob/master/chrome/script.browserify.js) area instead.

**Comment by maximbaz** [comment]
Depends on where you want to have the OTP code, in the popup or on top of the currently opened page in the browser?

The file `inject.browserify.js` is the script that gets injected in the actual page containing the form (but beware, if there are multiple iframes, it will be injected in all of them resulting in potentially multiple alerts / selectable boxes). If you want to have box displayed on the page, that's where to write the code.

The file `script.browserify.js` is the file that takes care of the popup itself.

Check out [CONTRIBUTING.md](https://github.com/dannyvankooten/browserpass/blob/master/CONTRIBUTING.md) for how to compile the code.

**Comment by ashkitten** [comment]
Good to know about the multiple iframes issue. Is there any way to detect the top-level document? I was thinking a prefilled input in the top-right of the page would be perfect.

**Comment by maximbaz** [comment]
Then put your code in a new file, inject it [here](https://github.com/dannyvankooten/browserpass/blob/aa50e1ba1d17f7480ec040f063c8806c08ad7ea5/chrome/background.js#L12-L24) but omit the `allFrames: true` parameter.

**Comment by ashkitten** [comment]
Gotcha
