### ISSUE TITLE
Sub directories not matched

### ISSUE THREAD

**Issue by Soullivaneuh** [dannyvankooten/browserpass#182]
### General information

* Operating system + version: Ubuntu 17.04
* Browser + version: Chrome Version 61.0.3163.100 (Official Build) (64-bit)
* If installed an official release, put a release version: 2.0.8

---

### Exact steps to reproduce the problem

With the following store map:

```
github
├── JoJo
└── Soullivaneuh
    └── pass
```

Search about `github` term on the extension.

### What should happen?

Having `github/JoJo` and `github/Soullivaneuh/pass` result.

### What happened instead?

Just having `github/JoJo`.

**Comment by maximbaz** [comment]
That's an interesting use-case. In principle I don't see any reason why not 🙂

Since it is a community project, it will be implemented only if you or someone else from the community decides to help out and provide a pull request. I'll be happy to test and review the code. 

The relevant bit of code:

https://github.com/dannyvankooten/browserpass/blob/d0619e5d35b0f4e269df5c2cd7abfcbc5d3cd7e0/pass/disk.go#L45-L47

**Comment by Soullivaneuh** [comment]
Well at least the issue is created. I don't have time right now, maybe later. :wink:

**Comment by bhhaskin** [comment]
It would be nice to be able to search subdirectories for domains as well.

I.e. personal/github.com/user; work/github.com/user

**Comment by maximbaz** [comment]
This is already supported, I use exactly that configuration:

![image](https://user-images.githubusercontent.com/1177900/33037989-7b5b431e-ce33-11e7-89fc-6eb1864d9d60.png)

**Comment by apropostech** [comment]
#196

**Comment by maximbaz** [comment]
Thanks to @apropostech for implementing this feature, will release v2.0.9 soon.
