### ISSUE TITLE
Update Installation Requirements for Mac OS X

### ISSUE THREAD

**Issue by Amar1729** [dannyvankooten/browserpass#205]
### General information

* OS X 10.11.6 (El Capitan)
* Chrome: 63.0.3239.132 (Official Build) (64-bit)
* browserpass release v2.0.9
* browserpass chrome extension v2.0.11

---

Didn't work upon first installation on Mac OS X, kept getting `"Error: Native host has exited"` message from Chrome. I ran Chrome from the command line, and used `./browserpass-darwinx64 < request.hex.txt` (recommended by #175) to debug the issue. I don't have the actual error anymore, but the problem was that I was missing some `gpg` stuff, and the following steps fixed it:

* `brew install gnupg pinentry-mac`
* manually symlink `/usr/local/bin/gpg2 -> ../Cellar/gnupg/<version>/bin/gpg`
* modify `~/.gnupg/gpg.conf`:
  * add the line `use-agent` to the end of the file (or uncomment it)
* modify `~/.gnupg/gpg-agent.conf`:
  * add the line `pinentry-program /usr/local/bin/pinentry-mac`
* reboot

Wasn't sure where you'd want this info in your README otherwise I would have submitted a PR. Thanks for the great extension!

**Comment by maximbaz** [comment]
Thanks! Please do make a PR, as to where to put this... Let's say, create a FAQ section after Security, and as a first sub-section create something like "Why it doesn't work on Mac? Error: Native host has exited". If you have a better suggestion, do not hesitate.

I'll comment more thoroughly on the contents in the PR, but it would be really really helpful if you could summarize all ideas from #13 in that section, because there is not one fix for all. Installing GPGtools and/or pinentry-mac seems like a must for everyone, ensuring gpg exists on one of the paths below (and otherwise creating a symlink) is a must too, modifying gpg.conf and gpg-agent.conf did help others, before reboot [also run `gpgconf --kill gpg-agent`](https://github.com/dannyvankooten/browserpass/issues/13#issuecomment-332634422) and maybe reboot is not needed. Sometimes starting browser from terminal helps, mention this too. Maybe I missed something from #13 🙂

https://github.com/dannyvankooten/browserpass/blob/1e464970a3a3b00a5679482177db7b3d5fe98a95/browserpass.go#L96-L100

**Comment by Amar1729** [comment]
Just going to dump relevant notes so this issue can be referenced in the PR.

Installed latest release of browserpass (v2.0.11) for Chrome on a clean MacOS system to test out the issues.

### Issue, Debugging

1. Installing the extension (from chrome store or .crx) and running `./install.sh` works fine, but I still get "Native host has exited" when trying to get a password for the current website.

2. Using [this file](https://github.com/dannyvankooten/browserpass/files/1367136/request.hex.txt) from #175 wasn't helpful since I don't have a github.com pw stored in my password store, and simply changing the domain to a different website resulted in an EOF error (maybe the file has to be re-generated?).

```
$ ./browserpass-darwinx64 < ~/Downloads/request.hex.txt
[]

$ ./browserpass-darwinx64 < ~/Downloads/request.hex.txt
[Browserpass] 2018/02/07 19:13:40 unexpected EOF
```

3. Tried running Chrome from terminal, and when trying to access a password I received:
```
[Browserpass] 2018/02/07 18:39:55 exit status 2
gpg: Sorry, we are in batchmode - can't get input
```

### Solution
1. `brew install gnupg pinentry-mac`
  - The homebrew formulae `gnupg` and `gnupg2` point to the same version (`gpg` = 2.2.4 as of 02/07/18), so installing either will work. As long as the `/usr/local/bin/gpg` symlink exists on a MacOS system, browserpass will find it.

2. Edit `~/.gnupg/gpg.conf`:
```
# comment or remove this line if it's there (it might be default uncommented in certain versions of gnupg):
#pinentry-mode loopback

# add this line:
use-agent
```

3. Add the following line to `~/.gnupg/gpg-agent.conf`:
```
pinentry-program /usr/local/bin/pinentry-mac
```

4. `gpgconf --kill gpg-agent` after editing `gpg.conf`, and restart Chrome (maybe not necessary to restart browser, but I did). Trying to get a password for a website should now pop up a gtk-like dialog asking for the password for your password store gpg key.
