### ISSUE TITLE
Try to submit form itself when submit button is not found

### ISSUE THREAD

**Issue by AuspeXeu** [dannyvankooten/browserpass#217]
I was wondering why the extension is looking to click a login button instead of submitting login form programatically. Any particular reason?

**Comment by maximbaz** [comment]
There is a reason, sadly many websites do not follow any kind of standards when implementing a login form, some don't specify the submit action on the form and instead rely on `on_click` handler on a "login" button, some don't even use the `<form>` tag at all. I found that looking for a login button is a universal solution that works better on most websites.

P.S. if I misunderstood the question and you are asking whether it is possible to make browserpass automatically submit the form for you, the answer is "yes", you can enable this in extension options.

**Comment by AuspeXeu** [comment]
This was exactly what I was asking, thanks for the quick response. Wouldn't it make it a bit more robust if you tried to submit the form first and then if that fails search for a button? :)

**Comment by maximbaz** [comment]
Well, what I like about the current behavior is that it "emulates" user as much as possible, for example if submit action differs from `on_click` action, since actual user would have clicked a button, extension is also made to click a button. Extension doesn't click too small or invisible buttons, just like user would not do.

Unless there is an issue with the current approach I wouldn't change it 🙂

**Comment by AuspeXeu** [comment]
Well, the main reason why I am asking is because this login form does not work :D

https://www.targobank.de/de/identification/login.cgi

It seems like the button is not recognised.

**Comment by maximbaz** [comment]
A perfect example of the funny markup, their login button is defined as an image `<input type=image`... 

But your request is reasonable. Today the behavior is the following: "try to click a submit button, if not found, put focus somewhere in the form so that user can just press Enter". Instead we could do "try to click a submit button, if not found, try to submit the form, if unsuccessful put focus somewhere in the form so that user can just press Enter".

**Comment by AuspeXeu** [comment]
Yeah, I haven't looked at the HTML itself. Seems like a good addition to try submitting the form before resorting to the focus option :)

**Comment by maximbaz** [comment]
Implemented in `master`, I'll publish a new release as soon as #213 is finished 🙂

Regarding `Unable to detect which of the multiple available forms is the login form`, thanks for letting me know! I'm collecting cases when extension cannot correctly guess the login form to improve the detection algorithm. It works fine on that particular website because the login form happens to be the first form on the page.

**Comment by maximbaz** [comment]
@AuspeXeu FYI this will be reverted in the next version, sorry. I found that this behavior breaks websites, for example discoverbank.com (#227) or aws.amazon.com (#268) who find the `.submit()` call to be either suspicious (only bot can fire this event, not human), or they just don't implement this. 

I focused instead on #271, auto-submit by emitting Enter keypress. This feels better, extension is simulating user's behavior, so less chances to get an undetermined behavior. However, for some unknown reasons this Enter keypress doesn't seem to be working on targobank.de.

I also considered to keep both, emitting Enter keypress event _and_ submitting the form, but this again doesn't work on sites like amazon.
