### ISSUE TITLE
Error "Native host has exited" since 2.0.12  -->  update host app!

### ISSUE THREAD

**Issue by maximbaz** [dannyvankooten/browserpass#218]
`2.0.12` introduced a breaking change, browser extension is not compatible with previous versions of the host app. Sorry for the inconvenience, please upgrade the host app 🙂

It is generally expected that users keep the versions in sync, but since browser extension auto-updates, such a breaking change will come as a surprise.

**Comment by raxod502** [comment]
How about making the browser extension check the version of the host app, and display an error message

> Host app is out of date (version 2.0.11), please install version 2.0.12

rather than

> Native host has exited

? Although it's still not ideal that the auto-updates cause breakage, I think this would eliminate any confusion.

**Comment by maximbaz** [comment]
Good idea, reporting meaningful errors is in general something I want very much (#164), however it's not trivial to implement 😞 

On the other hand you inspired me with #219, this should be a relatively cheap way to notify users of major changes.

**Comment by erayd** [comment]
@maximbaz

> Good idea, reporting meaningful errors is in general something I want very much (#164), however it's not trivial to implement.
> On the other hand you inspired me with #219, this should be a relatively cheap way to notify users of major changes

I'm concerned that #219 isn't sufficient - many users will just close the notification without reading it. It makes more sense IMO to provide a relevant message *at the point the user just experienced something go wrong*, when they're more likely to pay attention to such things.

Why not have the host app support a 'get version' call. That way, if you get an error, you can check the version of the host app in the error handling code. If it's a version mismatch causing the problem, then you can tell the user that, without needing to solve #164. This would have avoided the confusion caused by the 2.0.12 release.

Once #164 is sorted at some later date, you can change this behavior as needed.

**Comment by maximbaz** [comment]
I'm not saying that this is a bad idea (and I'm adding this entire idea to #164), but keep in mind that breaking changes are a rare event - this is the first one actually in the history of "community" version. In most cases, when a user experiences an issue, it is _not_ because of the version mismatch.

**Comment by tiramiseb** [comment]
Hello,

My two cents : you may implement a "protocol version" which would evolve independently. So v2.0.9 to v2.0.11 would use the same "protocol version", but 2.0.12 would use a different "protocol version"...

**Comment by tiramiseb** [comment]
Regarding update of the host app, keep in mind that some people use the distribution's version, which could be a few days late. So I think a comprehensive warning is important.
I'm using NixOS and first I wondered if I had a problem like #175, then after searching I realized it was not related to NixOS directly...

Yes, I could have checked https://github.com/dannyvankooten/browserpass/issues first. But we are not logical everyday, we are humans ;)

**Comment by Cogitri** [comment]
Sorry if I missed something about your versioning policy, but I feel like `version x introduced a breaking change` should result in at least the micro version to be increased, as of [sematic versioning](https://semver.org/)

**Comment by maximbaz** [comment]
Very good point, I should have done that...

**Comment by razic** [comment]
tips for windows users:

* if you don't have permission to save the json files, try opening notepad as an administrator first, then open the file. there was no option to open the json file in notepad as administrator from the right click menu on the json file itself.

* after installation, if you still see the "native host not found" message you may have forgotten to escape your backslashes. in json, backslashes are interpreted as escape sequences. tldr;

change 

```
C:\Program Files\Browserpass\browserpass-windows64.exe
```

to 
```
C:\\Program Files\\Browserpass\\browserpass-windows64.exe
```

i would say this should be pointed out better in the readme, but ideally the entire installation process on windows would be on par with the rest of the oses in terms of automation. at some point it might be cool to have gui installers for the native hosts.;

@maximbaz finally my only gripe ui wise so far is the white border on the top and bottom, which are not even the same width... really irks me every time i open it. the borders on the side look great, but would be nice to be consistent here.

![image](https://user-images.githubusercontent.com/225005/56083461-3120d600-5dda-11e9-995a-01bf37055fbf.png)

**Comment by max-baz** [comment]
Thanks @razic, I have included your hints in the README: https://github.com/browserpass/browserpass-native/commit/6d5b5d5cc2874831510bb271f00c0af1842c74dd

I agree that an automated installation would be very nice to have, but since no maintainer uses Windows, there's nobody to work on this. A community help is very welcome, if someone wants to help, create a new issue in [browserpass-native](https://github.com/browserpass/browserpass-native) and we will discuss details!

Wow these white borders is definitely something I have not seen yet, I will try to figure out what we can do about them.

**Comment by max-baz** [comment]
@razic quick googling shows that many extensions suffer the same fate on Windows, however turns out in the next version of Chrome this has been fixed! See the link below, it also links to pre-compiled binaries for Chromium 74 if you want to try now.

https://bugs.chromium.org/p/chromium/issues/detail?id=750419#c17

**Comment by razic** [comment]
@maximbaz lol not sure how this comment ended up on this thread, i totally meant to put it on the v3 feedback issue 🤦‍♂️ thanks for finding that border issue. chrome 74 is still beta so i'll wait until it they release  the stable build. i'll deal with the borders for now ;p i opened https://github.com/browserpass/browserpass-native/issues/48
