### ISSUE TITLE
broken signature in AUR repository

### ISSUE THREAD

**Issue by turboMaCk** [dannyvankooten/browserpass#223]
### General information
Hello!

It seems GPG signature for tarball in AUR is broken. I'm not sure if AUR has a different maintainer though.

* Operating system + version: Arch Linux
* Browser + version: Firefox
* Information about the host app: yaourt
  * If installed via package manager - yaourt
* Information about the browser extension:
  * Browserpass extension version as reported by your browser: problem's not there
---

### Exact steps to reproduce the problem
1. `yaourt -S browserpass`

### What should happen?
Browser pass installed

### What happened instead?
```
==> Verifying source file signatures with gpg...
    browserpass-2.0.12.tar.gz ... FAILED (unknown public key 011FDC52DA839335)
==> ERROR: One or more PGP signatures could not be verified!
==> ERROR: Makepkg was unable to build browserpass.
```

**Comment by maximbaz** [comment]
Unknown key means you have to retrieve the key first 🙂 I'll make a note of it on the AUR page.

I personally put `keyserver-options auto-key-retrieve` in my `~/.gnupg/gpg.conf` so that pacman is allowed to retrieve the keys automatically, but if you want to do this manually, do something like `gpg --recv-keys EB4F9E5A60D32232BB52150C12C87A28FEAC6B20` (or grab it from [keybase.io/maximbaz](https://keybase.io/maximbaz))

**Comment by turboMaCk** [comment]
Thank you! You're the best :raised_hands:
