### ISSUE TITLE
Remove old extension from Mozilla Registry

### ISSUE THREAD

**Issue by dragetd** [dannyvankooten/browserpass#254]
Hello,

it is a little confusing. It seems like Danny (dvko) stopped working on this last year, and the current maintainer Maxim took over.

But looking into the FireFox addon repository one finds two:
https://addons.mozilla.org/en-US/firefox/addon/browserpass/
https://addons.mozilla.org/en-US/firefox/addon/browserpass-ce/

It would be nice if the old (and to my findings currently nonfunctional one) could be removed by DVK so new people would have a clear match between the actual plugin and host app.

**Comment by maximbaz** [comment]
I really wish I could do that to avoid confusion, but as you imagine I don't have access 😞
It's difficult to get Danny's response, I sent him an email on a different topic, no answer so far.

@dannyvankooten if you see this notification, please delete the old extension, and check my email 😛

I'll close this because there is nothing else I can do, unfortunately.

**Comment by dannyvankooten** [comment]
Hey guys, done!

Sorry for being so absent @maximbaz. Life as a fresh parent is busier than I thought. It seems browserpass is in very good hands with you though, thank you for all the hard work thus far. You're the best. :+1:

**Comment by maximbaz** [comment]
Thanks @dannyvankooten! The other question I had for you is regarding the next major version for browserpass, it is currently being developed in a new org: https://github.com/browserpass

1. May we have your permission to keep using the name `browserpass` so that we don't have to rebrand and confuse people with yet another extension once it is ready?
2. Would you be willing to move this repo under the new org's umbrella, to have everything in one place? If yes, just transfer the repo to the org, or if that's simpler to my own account, and I'll move it further.

**Comment by dannyvankooten** [comment]
@maximbaz Done. Wasn't able to tranfer to the new organisation because I don't have rights, but made a request to transfer it to your account instead.

![image](https://user-images.githubusercontent.com/885856/38804982-8cab5938-4174-11e8-9b4d-b8cd96798b1a.png)

Would love to be on the organisation team so I can hopefully pick up in the future.

**Comment by maximbaz** [comment]
Just sent out the invite for the owner access to the org! Try to transfer the repo again directly to the org this time 🙂
