### ISSUE TITLE
Submitting login info fails for OTP

### ISSUE THREAD

**Issue by eterps** [dannyvankooten/browserpass#27]
Websites that use 2 factor authentication have two passwords, which can be detected by checking that there is more than one `input[type=password]` field.
When two `input[type=password]` fields are detected it is best to:

1) fill the password in the first one and
2) put the focus on the second one and avoiding the automatic submit so that the user can still login on these types of sites with browserpass

I'd love to contribute, any tips on how to develop and test this kind of thing?

**Comment by dannyvankooten** [comment]
Hey @eterps,

Nice catch! Do you have an example of a site that implements 2FA in the described way? 

Sites like Google for example simply ask for the 2FA key in a separate screen (since they know by then that the user account is using 2FA) but I'd love to have a real live test case for this.

As for contributing, it's probably easiest to clone the repository and then import the Chrome or Firefox add-on development folder in the browser. In this case it's probably a one-line change in the methodh ere: [/chrome/script.browserify.js#L134](https://github.com/dannyvankooten/browserpass/blob/master/chrome/script.browserify.js#L134)

**Comment by eterps** [comment]
Hi @dannyvankooten a nice and clear example is: https://www.kraken.com/en-us/login
