### ISSUE TITLE
"Not available for your platform" on Firefox 52.0b7 64bit on Linux

### ISSUE THREAD

**Issue by paulolieuthier** [dannyvankooten/browserpass#41]
When opening browserpass page on addons.mozilla.org, I get the message saying it's not available for my platform, although I'm using Firefox Beta on Arch Linux. What am I not seeing?

**Comment by maximbaz** [comment]
I've just tried the current Firefox Beta from AUR, seems to be fine. I imagine this is an old issue, and it has simply been fixed since then. I'll close it for now for cleanup purposes, but please do try again and reopen if you still experience the issue.

![image](https://user-images.githubusercontent.com/1177900/30459849-670c0ba0-99b3-11e7-9dd7-804024cc6321.png)
