### ISSUE TITLE
Order search results by match.

### ISSUE THREAD

**Issue by dannyvankooten** [dannyvankooten/browserpass#49]
Since #44, the browser plugin searches for the top level domain. However this makes it so that when searching for `google.com`, a login for `accounts.google.com` (exact match) will not be shown. 

We should probably search for both strings, showing exact matches first in the list followed by the other (modified match) results.

**Comment by opatut** [comment]
How about fuzzy matching? I don't know how to do this in Go, but in JS one could use [mattyork/fuzzy](https://github.com/mattyork/fuzzy) or similar. Maybe you can find something like that in Go?

**Comment by opatut** [comment]
https://github.com/renstrom/fuzzysearch

**Comment by maximbaz** [comment]
Since #213 fuzzy search is enabled by default, and it does not suffer from this problem - manually searching for `google.com` does find `account.google.com` entries.

Glob search is not removed (and can be used if you explicitly turn off fuzzy search in the options), but its main purpose is to serve the automatic domain match - and automatic domain match should not find `account.google.com` when you are on `https://google.com` (if you want this, you should explicitly do this by renaming the file in password store to `google.com.gpg`).

Because of this, I will close the ticket. If you have a special need, where you don't want to enable fuzzy search and yet need this feature, please let me know. Pull requests are welcome too.
