### ISSUE TITLE
Make userfield configurable.

### ISSUE THREAD

**Issue by carnager** [dannyvankooten/browserpass#57]
Hey, I am the author of [rofi-pass](https://github.com/carnager/rofi-pass) which is around for a while now. 
browserpass seems to follow a similar style of pass files, but uses "login" instead of "user" in default setup. From what I can see this is not configurable in browserpass.

in rofi-pass i allow to set a custom fieldname. Maybe you would consider to do the same, which would result in those 2 projects being compatible with each other, if one wishes to do.

**Comment by maximbaz** [comment]
Hey there, it is not configurable because we simply support all available options 🙂

Currently, `login:`, `username:` and `user:` are supported:

https://github.com/dannyvankooten/browserpass/blob/de51df0952e49276b5ad7d7da1d96ebb2d253688/browserpass.go#L179-L180

I'm surprised that this requested stayed open since March without a reply, because the `user:` fieldname is supported since December 2016 - https://github.com/dannyvankooten/browserpass/commit/42751b5e8b149b005a9884a7eaed9b763bf64aa2.

I double checked by creating an entry with `user:` in it - works fine, thus closing. Let me know if I missed something here.
