### ISSUE TITLE
Make shortcut configurable

### ISSUE THREAD

**Issue by jplitza** [dannyvankooten/browserpass#60]
After #11, the new Shortcut Alt+Shift+L again causes problems in Firefox if its locale is German, because the bookmark menu ("Lesezeichen") is opened with Alt+L, and the additional Shift regrettably doesn't prevent this.

The only way that ensures everyone can use a shortcut that doesn't conflict with anything else (also: global hotkeys they defined) would be to make it configurable.

**Comment by dannyvankooten** [comment]
Hey @jplitza,

Great suggestion, I actually thought that Firefox allowed this by default but it seems as if this is only possible in Chrome.

**Comment by maximbaz** [comment]
Unfortunately this is something that has to be fixed in Firefox. We are defining the shortcut in the manifest, way before our code is running, and we are using the property called [`suggested_key`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands). That's right, it is *suggested*, and browsers must provide a way to override it. Chrome does, there is "Keyboard shortcuts" button in the bottom of the `chrome://extensions` page. But Firefox is new to this extension model, and haven't implemented this window yet.

I'll close this issue since we cannot (don't want to?) implement a custom dialog to choose shortcut, it is the responsibility of a browser.

What I can offer you though is a discussion on choosing a better default shortcut. Just created an discussion issue for this, leave your thoughts there - #160.
