### ISSUE TITLE
Support gopass mounts

### ISSUE THREAD

**Issue by adius** [dannyvankooten/browserpass#77]
We use gopass at work and therefore I've mounted the companies password store in my personal one.
This means there is `google.com/john@doe.com` and `company-name/google.com/john@company-name.com`
Those company entries however don't show up in browserpass.

**Comment by martinhoefling** [comment]
What would be the best way to implement this. the browserpass searches for the password store and then in it's subdirectories and does not use pass/gopass for this task. I could imagine to implement the Store interface with methods with shell out to gopass. Any other ideas?

**Comment by mjrider** [comment]
@martinhoefling vendoring the gopass code, and calling the subroutines directly instead of re-implementing the same wheel and/or using shell execution?

**Comment by maximbaz** [comment]
Gopass mounts are not physical subdirectories in `.password-store`, otherwise they would have been discovered by browserpass. On the one hand, I like not reimplementing wheels, on the other hand the current code is not using `pass` since #6, so it is not as simple as just replacing `pass` with `gopass` everywhere in the code. 

Since current code is handling fine one password-store, maybe yet another approach would be to make an option to define paths to multiple password stores somewhere in extension config, and reuse the same code as we have now?

**Comment by adius** [comment]
👉  make an option to define paths to multiple password stores somewhere in extension config

**Comment by maximbaz** [comment]
This would be an awesome next addition to the project. I see this as a list of entries on the options page, with a checkbox next to each entry so that we can configure the list of password stores once, and toggle which ones are needed (such toggling functionality is requested in #98).

The options page was recently created in #95.

The primary challenge here I think is communicating from browser to host app this list of active password stores, and making sure the list doesn't go out of sync between the browser and the host app. Once this list is available in the host app, wrapping the existing code in a loop should not be big of a deal.

So... anyone up for a challenge? 🙂

**Comment by zsau** [comment]
My purposes would be served by a one-store-per-container model. Do others want to have multiple stores active at one time, or maybe the ability to switch between stores on-the-fly without using containers?

**Comment by maximbaz** [comment]
I personally understood this ticket as specifically about many-to-one model, where there are multiple password stores (one personal and one for work), and people want to combine both of them and see credentials from both in the single browser/browserpass instance. 

The gopass is a CLI tool that "virtually" combines many password stores in one, here it is asked about the same thing for browserpass.

**Comment by erayd** [comment]
I concur. I don't actually need this (one password store is fine for my purposes), however if I was using multiple stores, I would want them all active simultaneously.

Needing to manually switch stores depending on the login being used would be a significant and annoying bottleneck in the password-filling workflow.

**Comment by martinhoefling** [comment]
If you're interested in a browser plugin working with gopass, have a look at [gopassbridge](https://github.com/martinhoefling/gopassbridge). The UI is heavily inspired from browserpass which I originally used with gopass before writing that extension.

**Comment by maximbaz** [comment]
Hey guys, please share your thoughts on [an idea to make this browser extension support `gopass` host](https://github.com/dannyvankooten/browserpass/issues/194).

**Comment by maximbaz** [comment]
Implemented in PR #237, will release after a few days of testing myself. Early feedback is welcome.
